### ISSUE TITLE
Failed to run `shadowray --subscribe-update'

### ISSUE THREAD

**Issue by hongyi-zhao** [RMTT/Shadowray#4]
Hi,

I use Debian 9 and installed the shadowray as follows:

 $ pip install shadowray

Then do some config:

$ shadowray --autoconfig
$ shadowray --subscribe-add 'kitsunebi_sub,https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub'
$ shadowray --subscribe-add 'youlianboshi.netlify.com,https://youlianboshi.netlify.com/'
$ shadowray --subscribe-add 'v2ray.qlolp.ml,https://v2ray.qlolp.ml'

Then do the update:

$ shadowray --subscribe-update
update youlianboshi.netlify.com : https://youlianboshi.netlify.com/
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.7.4/bin/shadowray", line 10, in <module>
    sys.exit(main())
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/shadowray/__init__.py", line 330, in main
    update_subscribe(port=port)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/shadowray/__init__.py", line 204, in update_subscribe
    manager.update_subscribe(show_info=True, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/shadowray/core/manager.py", line 23, in update_subscribe
    self.__subscribe.update(show_info=show_info, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/shadowray/subscribe/parser.py", line 74, in update
    self.get_url(self.subscribes[j], **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/shadowray/subscribe/parser.py", line 32, in get_url
    t[1] = json.loads(decode(t[1]))
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any hints for this issue?

**Comment by RMTT** [comment]
Maybe you should verify the content of subscribes, whether the original text is json format.
This error is very common in python.V2ray has not a standard format of subscribe, so i cannot deal kinds of subscribe.So,you can solve the problem by yourself firstly, and then post your solution.Maybe I can improve shadowray on the next version.Good luck to you.
